/**
 * Negative statuses that nonetheless land on FRIENDLY units.
 *
 * The parser decides an "applies <status>" clause's side from the status's `type` in
 * src/constants/buffs.ts, where these are (correctly) typed `debuff` — they are bad for the
 * carrier. But side and valence are different questions: Barrier Recharging is the
 * self-inflicted cooldown that pays for a Barrier grant, so it belongs on the granter's own
 * team. Without this override, Quixilver's "…and applies Barrier Recharging for 3 turns" routes
 * to the enemy, where it does nothing at all (and the lockout it is supposed to impose never
 * binds).
 *
 * Panon reaches the right side today only because its text says "to itself" explicitly; this set
 * is what makes the receiver-less phrasing work too.
 *
 * Lives here rather than in src/constants/buffs.ts because that file is regenerated by
 * `npm run fetch-buffs` and would clobber hand-authored entries — same reason as
 * persistentStackingBuffs.ts and oneShotPersistentBuffs.ts.
 */
export const FRIENDLY_SIDE_STATUSES: ReadonlySet<string> = new Set(['Barrier Recharging']);

export const isFriendlySideStatus = (name: string): boolean => FRIENDLY_SIDE_STATUSES.has(name);
