export const JOKES = [
    'Why did the sun go to school? To get brighter!',
    'What kind of music do planets like? Nep-tunes!',
    "What do you call a star that doesn't shower? A smelly dwarf!",
    'Why did the asteroid go to the doctor? It had asteroid belt problems!',
    'What did Mars say to Saturn? Give me a ring sometime!',
    "Why don't aliens eat M&Ms? They're looking for life on Mars bars!",
    "What do you call a black hole that's a neat freak? A vacuum cleaner!",
    'How do astronauts organize a party? They planet!',
    'What did the meteorologist say to the falling star? Nice to meteor!',
    "Why did the constellation go to the doctor? It had Orion's Belt!",
    "What's an astronaut's favorite part of the computer? The space bar!",
    "Why don't planets like online shopping? They prefer space-ship delivery!",
    "What do you call a star that's a bit too bright? A supernova!",
    "I'm not saying earth's sky is the prettiest, but it's up there! (My wife made this one)",
    'What do you call a space wizard? A shooting star!',
    'What kind of pictures do astronauts take? Selfie-ites!',
    'Why did the sun skip college? It already has millions of degrees!',
    'What do you call a space outlaw? A rocket-eer!',
    'How does the solar system hold up its pants? With an asteroid belt!',
    'What did the astronomer say when he walked into a wall? "At least the sky\'s the limit!"',
    'Why did the astronaut break up with the satellite? She needed some space!',
    'What do planets use to download music? Neptune!',
    'Why did the astronaut leave the party? Because there was no atmosphere!',
    'What do you call an alien with three eyes? An aliiien!',
    'How does the alien style its hair? With a comet!',
    'What do you call a ripped space cow? The Milky Whey!',
    'What kind of songs do planets sing? Nep-tunes!',
    'What did the alien say to the garden? Take me to your weeder!',
    "What do you call a space station's favorite meal? Launch!",
    'How do aliens serve dinner? On flying saucers!',
    'What did the Moon say to the Sun? "You\'re the light of my life!"',
    "Why don't Martians have birthday parties? They're already in their space year!",
    "What do you call a star that's always complaining? A SOL-ar whiner!",
    'How do astronauts handle conflict? They apollo-gize!',
    "What's an astronaut's favorite social media? MySpace!",
    'Why did the telescope go to the optometrist? It needed some space-tacles!',
    'What do you call a star that sneezes? A pulsar!',
    'How do planets stay warm? They use space heaters!',
    'What did Mars say to Venus? "You\'re out of this world!"',
];

export const getRandomJoke = () => JOKES[Math.floor(Math.random() * JOKES.length)];
