export const JOKES = [
    'Why did the sun go to school? To get brighter!',
    'What kind of music do planets like? Nep-tunes!',
    "What do you call a star that doesn't shower? A smelly dwarf!",
    'Why did the asteroid go to the doctor? It had asteroid belt problems!',
    'What did Mars say to Saturn? Give me a ring sometime!',
    "Why don't aliens eat M&Ms? They're looking for life on Mars bars!",
    "What do you call a black hole that's a neat freak? A vacuum cleaner!",
    'How do astronauts organize a party? They planet!',
    'What did the meteorologist say to the falling star? Nice to meteor!',
    "Why did the constellation go to the doctor? It had Orion's Belt!",
    "What's an astronaut's favorite part of the computer? The space bar!",
    "Why don't planets like online shopping? They prefer space-ship delivery!",
    "What do you call a star that's a bit too bright? A supernova!",
    'Why did the asteroid go to the doctor? It had asteroid belt problems!',
    'What did Mars say to Saturn? Give me a ring sometime!',
    "Why don't aliens eat M&Ms? They're looking for life on Mars bars!",
    "What do you call a black hole that's a neat freak? A vacuum cleaner!",
    'How do astronauts organize a party? They planet!',
    'What did the meteorologist say to the falling star? Nice to meteor!',
    "Why did the constellation go to the doctor? It had Orion's Belt!",
    "What's an astronaut's favorite part of the computer? The space bar!",
    "Why don't planets like online shopping? They prefer space-ship delivery!",
    "What do you call a star that's a bit too bright? A supernova!",
    'Why did the asteroid go to the doctor? It had asteroid belt problems!',
    'What did Mars say to Saturn? Give me a ring sometime!',
    "Why don't aliens eat M&Ms? They're looking for life on Mars bars!",
    "What do you call a black hole that's a neat freak? A vacuum cleaner!",
    'How do astronauts organize a party? They planet!',
    'What did the meteorologist say to the falling star? Nice to meteor!',
    "Why did the constellation go to the doctor? It had Orion's Belt!",
    "What's an astronaut's favorite part of the computer? The space bar!",
    "Why don't planets like online shopping? They prefer space-ship delivery!",
];

export const getRandomJoke = () => JOKES[Math.floor(Math.random() * JOKES.length)];
