import { PERSISTENT_STACKING_BUFFS } from './persistentStackingBuffs';

/**
 * ONE-SHOT statuses that persist until CONSUMED rather than expiring on a timer.
 *
 * These route to the same persistent status store as PERSISTENT_STACKING_BUFFS, which means
 * their parsed duration is deliberately ignored — the buff-name rule overrides it, exactly as
 * it already does for the stacking family (statusEngine's persistent routing).
 *
 * Why that matters here: neither status states a duration in its own game text. Sentinel's
 * `Charged Overdrive II` only LOOKS like it has one because the parser's backward duration scan
 * leaks the preceding clause's "for 3 turns" onto it ("grants Out. Damage Up III for 3 turns and
 * Charged Overdrive II"). Name-keying makes that leak irrelevant without touching the parser —
 * see the design doc for why the parser fix is deferred (the naive positional rule regresses
 * Oleander).
 *
 * The store this routes to is surfaced by `timedAbilityStatuses` and cleared by
 * `removeSelfBuffByName`, which is precisely the read/consume pair a one-shot requires: every
 * channel the read can see, the consume call can spend.
 *
 * Lives here rather than in src/constants/buffs.ts because that file is regenerated by
 * `npm run fetch-buffs` and would clobber hand-authored entries — same reason as
 * persistentStackingBuffs.ts.
 *
 * NOT a member, deliberately: `Charge Overdrive II` (buffs.ts). Despite the near-identical name
 * and the identical +20% Defense Penetration magnitude, that one is a STANDING buff. This one is
 * scoped to "the next Charged Skill activation". Do not normalize them together.
 */
export const ONE_SHOT_PERSISTENT_BUFFS: ReadonlySet<string> = new Set([
    'Shield Converter',
    'Charged Overdrive II',
]);

/**
 * Membership test for the persistent store — true for BOTH the stacking family and the one-shot
 * family. This is the predicate every routing site should use; it is the union, not a replacement.
 */
export function isPersistentByName(buffName: string): boolean {
    return PERSISTENT_STACKING_BUFFS.has(buffName) || ONE_SHOT_PERSISTENT_BUFFS.has(buffName);
}

/**
 * Stack cap for a persistent name. One-shots cap at 1 (a second application must not let a single
 * consume call leave a residue behind).
 *
 * Returns `undefined` for BOTH "uncapped stacking name" and "not persistent at all" — same
 * ambiguity `PERSISTENT_STACKING_BUFFS.get` already has. Callers must gate on
 * {@link isPersistentByName} first, exactly as the existing code gates on `.has`.
 */
export function persistentCapFor(buffName: string): number | undefined {
    if (ONE_SHOT_PERSISTENT_BUFFS.has(buffName)) return 1;
    return PERSISTENT_STACKING_BUFFS.get(buffName);
}
