/**
 * Persistent stacking statuses (game-verified 2026-06-05).
 *
 * Certain stackable buffs/debuffs are NOT timed, regardless of what the skill text
 * says: each landed application adds a stack (capped at the buff DB's max) and the
 * status persists until its own removal rule (below) or a cleanse/purge takes it.
 *
 * The buff-name rule OVERRIDES skill-text durations: Enforcer's skill text says
 * "inflicts Defense Shred for 3 turns", but in-game the stacks persist and climb —
 * the name wins over the text duration.
 *
 * - Defense Shred (max 20, -2% Defense/stack) — persists until cleansed.
 * - Blast (max 4, +15% Outgoing/stack) — persists.
 * - Overload (max 10) — persists until the unit kills an enemy. The combat sim
 *   now models that lose-on-kill via the remove-self-buff path. In the DPS
 *   calculator it stays permanent: the dummy enemy is indestructible, so the
 *   kill never fires there.
 * - Titanite Plating (max 5) — persists, loses 1 stack each time its holder takes direct
 *   damage (`TITANITE_PLATING`; spent in the engine's damage funnel beside Exposed).
 *
 * Deliberately ABSENT:
 * - Warding Screen ("Stackable up to 4") — unverified in-game. OPEN QUESTION: if it
 *   turns out to be persistent like the four above, add it here; otherwise it stays on
 *   the timed family path. Left out until confirmed.
 * - Defense Matrix — genuinely TIMED (its skill texts carry "for x turns"); it stays on
 *   the family-rule timed path. Do NOT add it here.
 *
 * NOTE: this list lives here (not in src/constants/buffs.ts) because buffs.ts is
 * regenerated by `npm run fetch-buffs` and would clobber hand-authored entries.
 *
 * Map value is the max stack count (cap); `undefined` means uncapped.
 */
export const PERSISTENT_STACKING_BUFFS: ReadonlyMap<string, number | undefined> = new Map<
    string,
    number | undefined
>([
    ['Defense Shred', 20],
    ['Blast', 4],
    ['Overload', 10],
    ['Titanite Plating', 5],
]);

/** "Removes one stack after taking direct damage." The engine spends one stack per landed direct
 *  hit, on the same predicate that spends an Exposed stack (`applyVictimDamage`). */
export const TITANITE_PLATING = 'Titanite Plating';
