import React, { useState, useMemo } from 'react';
import { CraftingSuggestion } from '../../types/crafting';
import { GEAR_SLOTS } from '../../constants/gearTypes';
import { SHIP_TYPES } from '../../constants';
import { SET_MATERIAL_REQUIREMENTS, MATERIAL_SOURCES } from '../../constants/craftingProbabilities';
import { Tabs } from '../ui/layout/Tabs';

interface Props {
    suggestions: CraftingSuggestion[];
    onSelectSuggestion?: (suggestion: CraftingSuggestion) => void;
}

/**
 * Formats a score for display, using commas for thousands and abbreviating very large numbers
 */
function formatScore(score: number): string {
    if (score >= 1000000) {
        return (score / 1000000).toFixed(1) + 'M';
    }
    if (score >= 1000) {
        return (score / 1000).toFixed(1) + 'K';
    }
    return Math.round(score).toLocaleString();
}

export const CraftingSuggestions: React.FC<Props> = ({ suggestions, onSelectSuggestion }) => {
    // Group suggestions by role
    const suggestionsByRole = useMemo(() => {
        const grouped: Record<string, CraftingSuggestion[]> = {};
        suggestions.forEach((suggestion) => {
            if (!grouped[suggestion.role]) {
                grouped[suggestion.role] = [];
            }
            grouped[suggestion.role].push(suggestion);
        });
        return grouped;
    }, [suggestions]);

    // Create tabs from roles, sorted by role name
    const roleTabs = useMemo(() => {
        return Object.keys(suggestionsByRole)
            .sort((a, b) => {
                const nameA = SHIP_TYPES[a]?.name || a;
                const nameB = SHIP_TYPES[b]?.name || b;
                return nameA.localeCompare(nameB);
            })
            .map((role) => ({
                id: role,
                label: SHIP_TYPES[role]?.name || role,
            }));
    }, [suggestionsByRole]);

    const [activeRole, setActiveRole] = useState<string>(roleTabs.length > 0 ? roleTabs[0].id : '');

    // Update active role if current one has no suggestions
    React.useEffect(() => {
        if (roleTabs.length > 0 && !suggestionsByRole[activeRole]) {
            setActiveRole(roleTabs[0].id);
        }
    }, [activeRole, roleTabs, suggestionsByRole]);

    const activeSuggestions = suggestionsByRole[activeRole] || [];

    if (suggestions.length === 0) {
        return (
            <div className="text-center py-8 text-gray-400">
                <p>No crafting suggestions available.</p>
                <p className="text-sm mt-2">
                    Suggestions are based on comparing your top 30 gear scores per slot/role.
                </p>
                <p className="text-sm mt-2">Suggestions appear when:</p>
                <ul className="text-sm mt-2 text-left max-w-md mx-auto list-disc list-inside">
                    <li>You have fewer than 30 pieces for a slot/role combination</li>
                    <li>The average score of your top 30 pieces is 10%+ higher than the median</li>
                </ul>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            <div className="bg-blue-900/20 border border-blue-700/50 p-4 mb-4">
                <h3 className="font-semibold text-blue-300 mb-2">How Suggestions Work</h3>
                <p className="text-sm text-gray-300">
                    Suggestions are generated by analyzing your gear inventory. For each slot and
                    role combination, we calculate scores for all your gear pieces using the same
                    scoring system as upgrade analysis (with test stats: 30k HP, 8k ATK/DEF, etc.).
                    If the average of your top 30 pieces is significantly higher than the median, it
                    suggests you have some excellent pieces but could benefit from more gear of that
                    type. We then match craftable set bonuses to your role needs.
                </p>
                <p className="text-sm text-gray-400 mt-2">
                    <strong>Note:</strong> Scores are role-specific and can vary significantly
                    between roles (e.g., Defender Security scores are typically much higher than
                    other roles). The important metric is the gap between average and median, not
                    the absolute score values.
                </p>
            </div>

            <div className="bg-yellow-900/20 border border-yellow-700/50 p-4 mb-4">
                <h3 className="font-semibold text-yellow-300 mb-2">Material Sources</h3>
                <p className="text-sm text-gray-300">
                    Crafting materials can be obtained from:{' '}
                    <strong>{MATERIAL_SOURCES.faction_ops}</strong> and{' '}
                    <strong>{MATERIAL_SOURCES.dispatch}</strong> game modes.
                </p>
            </div>

            {roleTabs.length > 1 && (
                <Tabs tabs={roleTabs} activeTab={activeRole} onChange={setActiveRole} />
            )}

            {activeSuggestions.length === 0 ? (
                <div className="text-center py-8 text-gray-400">
                    <p>No suggestions for {SHIP_TYPES[activeRole]?.name || activeRole} role.</p>
                </div>
            ) : (
                <div className="space-y-3">
                    {activeSuggestions.map((suggestion, index) => {
                        const slotLabel = GEAR_SLOTS[suggestion.slot]?.label || suggestion.slot;
                        const materialType = SET_MATERIAL_REQUIREMENTS[suggestion.suggestedSet];
                        const materialLabel =
                            materialType === 'synth_alloy' ? 'Synth Alloy' : 'Quantum Fiber';

                        return (
                            <div
                                key={`${suggestion.slot}-${suggestion.role}-${index}`}
                                className="bg-dark-lighter border border-dark-border p-4 hover:border-primary transition-colors"
                            >
                                <div className="flex justify-between items-start mb-2">
                                    <div>
                                        <h3 className="font-semibold text-lg">{slotLabel}</h3>
                                        <p className="text-sm text-gray-400 mt-1">
                                            Suggested Set:{' '}
                                            <strong>{suggestion.suggestedSet}</strong> (
                                            {materialLabel})
                                        </p>
                                    </div>
                                    {onSelectSuggestion && (
                                        <button
                                            onClick={() => onSelectSuggestion(suggestion)}
                                            className="px-4 py-2 bg-primary text-dark hover:bg-primary/90 transition-colors text-sm font-medium"
                                        >
                                            Use in Calculator
                                        </button>
                                    )}
                                </div>

                                <div className="mt-3 space-y-2">
                                    <div className="flex justify-between text-sm">
                                        <span className="text-gray-400">Average Score:</span>
                                        <span className="font-semibold">
                                            {formatScore(suggestion.averageScore)}
                                        </span>
                                    </div>
                                    <div className="flex justify-between text-sm">
                                        <span className="text-gray-400">Median Score:</span>
                                        <span className="font-semibold">
                                            {formatScore(suggestion.medianScore)}
                                        </span>
                                    </div>
                                    {suggestion.medianScore > 0 && (
                                        <div className="flex justify-between text-sm">
                                            <span className="text-gray-400">Gap:</span>
                                            <span className="font-semibold text-yellow-400">
                                                {(
                                                    ((suggestion.averageScore /
                                                        suggestion.medianScore -
                                                        1) *
                                                        100) |
                                                    0
                                                ).toFixed(0)}
                                                % higher
                                            </span>
                                        </div>
                                    )}
                                </div>

                                <div className="mt-3 pt-3 border-t border-dark-border">
                                    <p className="text-sm text-gray-300">{suggestion.reasoning}</p>
                                </div>
                            </div>
                        );
                    })}
                </div>
            )}
        </div>
    );
};
